import { useState, useEffect } from 'react';
import { adminApi } from '../../api/admin.api';
import { useToast } from '../ui/Toast';
import Button from '../ui/Button';
import Input from '../ui/Input';

const initialStop = { hubId: '', sequenceNumber: 1, arrivalTime: '', departureTime: '', distanceFromOriginKm: 0 };
export default function RouteManager() {
  const [trains, setTrains] = useState([]); const [stations, setStations] = useState([]); const [selectedTrain, setSelectedTrain] = useState(''); const [creating, setCreating] = useState(false); const [stops, setStops] = useState([initialStop]); const showToast = useToast();
  useEffect(() => { adminApi.getVehicles().then((res) => setTrains(res.data || [])).catch((err) => showToast(err.message || 'Failed to load vehicles', 'error')); adminApi.getHubs(1, 100).then((res) => setStations(res.data || [])).catch((err) => showToast(err.message || 'Failed to load hubs', 'error')); }, []);
  const addStop = () => setStops([...stops, { ...initialStop, sequenceNumber: stops.length + 1 }]);
  const removeStop = (index) => setStops(stops.filter((_, stopIndex) => stopIndex !== index));
  const updateStop = (index, field, value) => { const updated = [...stops]; updated[index] = { ...updated[index], [field]: value }; setStops(updated); };
  const handleCreate = async (event) => { event.preventDefault(); if (!selectedTrain) { showToast('Select a vehicle', 'warning'); return; } setCreating(true); try { const hubs = stops.map((stop) => ({ hubId: stop.hubId, sequenceNumber: parseInt(stop.sequenceNumber, 10), arrivalTime: stop.arrivalTime || null, departureTime: stop.departureTime || null, distanceFromOriginKm: parseFloat(stop.distanceFromOriginKm) || 0 })); await adminApi.createTransportRoute({ vehicleId: selectedTrain, hubs }); showToast('Transport route created!', 'success'); setSelectedTrain(''); setStops([initialStop]); } catch (err) { showToast(err.message, 'error'); } finally { setCreating(false); } };
  return <form onSubmit={handleCreate} className="admin-create-panel admin-route-panel"><h2>Create Transport Route</h2><div className="admin-create-body"><div className="admin-select-field"><label htmlFor="route-vehicle">Vehicle / Service</label><select id="route-vehicle" value={selectedTrain} onChange={(event) => setSelectedTrain(event.target.value)} className="input-field" required><option value="">Select a vehicle</option>{trains.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.vehicleNumber} — {vehicle.vehicleName}</option>)}</select></div><h3>Route Hubs</h3><div className="admin-dynamic-list route-hubs">{stops.map((stop, index) => <fieldset key={index}><legend>Route hub {index + 1}</legend><div><label htmlFor={`route-hub-${index}`}>Hub</label><select id={`route-hub-${index}`} value={stop.hubId} onChange={(event) => updateStop(index, 'hubId', event.target.value)} className="input-field" required><option value="">Select hub</option>{stations.map((hub) => <option key={hub.id} value={hub.id}>{hub.name} ({hub.code})</option>)}</select></div><Input label="Sequence" type="number" value={stop.sequenceNumber} onChange={(event) => updateStop(index, 'sequenceNumber', event.target.value)} required /><Input label="Arrival" type="time" value={stop.arrivalTime} onChange={(event) => updateStop(index, 'arrivalTime', event.target.value)} /><Input label="Departure" type="time" value={stop.departureTime} onChange={(event) => updateStop(index, 'departureTime', event.target.value)} /><Input label="Distance (km)" type="number" min="0" step="0.01" value={stop.distanceFromOriginKm} onChange={(event) => updateStop(index, 'distanceFromOriginKm', event.target.value)} />{stops.length > 1 && <button type="button" className="admin-remove-row" aria-label={`Remove route hub ${index + 1}`} onClick={() => removeStop(index)}>×</button>}</fieldset>)}</div><div className="admin-form-actions"><Button type="button" variant="secondary" onClick={addStop}>Add Hub</Button><Button type="submit" loading={creating}>Create Route</Button></div></div></form>;
}
